name: First Workflow

on: workflow_dispatch

jobs:
  some-job-name:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hello World!"
      - name: print goodbye
        run: echo "Done - Bye!!"
        
